export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const PRODUCTS_DETAIL_REQUEST= 'PRODUCTS_DETAIL_REQUEST'
export const PRODUCTS_DETAIL_SUCCESS= 'PRODUCTS_DETAIL_SUCCESS'
export const PRODUCTS_DETAIL_FAIL= 'PRODUCTS_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'